import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { init } from "@pipedrive/app-extensions-sdk";
import { useEffect } from "react";
export default function Home() {
  useEffect(() => {
    async function openCustomFrontendModal() {
      const urlParams = new URLSearchParams(window.location.search);
      const identifier = urlParams.get("id"); // Assuming the identifier is passed as 'id' in the URL query

      if (!identifier) {
        console.error("Identifier not found in URL query parameters.");
        return;
      }

      const { modal } = await init();

      modal.setTitle("Custom Frontend");
      modal.setContent(
        `<iframe src="/custom_frontend?id=${encodeURIComponent(
          identifier
        )}" frameborder="0" style="width: 100%; height: 100%;"></iframe>`
      );
      modal.setWidth("90%");
      modal.setHeight("90%");
      modal.setIsFullWidth(true);
      modal.setIsFullHeight(true);
      modal.setIsHiddenOnClose(false);

      modal.open();
    }

    openCustomFrontendModal();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>My title</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
